// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decrypt(arg1, arg2, arg3) {
  return window['go']['main']['App']['Decrypt'](arg1, arg2, arg3);
}

export function Encrypt(arg1, arg2, arg3) {
  return window['go']['main']['App']['Encrypt'](arg1, arg2, arg3);
}

export function ReadKeyAndTextFromFile(arg1) {
  return window['go']['main']['App']['ReadKeyAndTextFromFile'](arg1);
}

export function SaveKeyAndResultToFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveKeyAndResultToFile'](arg1, arg2, arg3);
}
