// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Decrypt(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Encrypt(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ReadKeyAndTextFromFile(arg1:string):Promise<main.FileData>;

export function SaveKeyAndResultToFile(arg1:string,arg2:string,arg3:string):Promise<void>;
